import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontManrope = localFont({
  src: "./fonts/Manrope.woff2",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className={`h-full antialiased ${fontManrope.className}`}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
